/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RsvpPreviewRouteImport } from './routes/rsvp.preview'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInvitationsNewRouteImport } from './routes/_authenticated/invitations.new'

const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpPreviewRoute = RsvpPreviewRouteImport.update({
  id: '/rsvp/preview',
  path: '/rsvp/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvitationsNewRoute =
  AuthenticatedInvitationsNewRouteImport.update({
    id: '/invitations/new',
    path: '/invitations/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/restaurants': typeof RestaurantsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/rsvp/preview': typeof RsvpPreviewRoute
  '/invitations/new': typeof AuthenticatedInvitationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/restaurants': typeof RestaurantsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/rsvp/preview': typeof RsvpPreviewRoute
  '/invitations/new': typeof AuthenticatedInvitationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/restaurants': typeof RestaurantsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/rsvp/preview': typeof RsvpPreviewRoute
  '/_authenticated/invitations/new': typeof AuthenticatedInvitationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/restaurants'
    | '/dashboard'
    | '/rsvp/$token'
    | '/rsvp/preview'
    | '/invitations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/restaurants'
    | '/dashboard'
    | '/rsvp/$token'
    | '/rsvp/preview'
    | '/invitations/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/restaurants'
    | '/_authenticated/dashboard'
    | '/rsvp/$token'
    | '/rsvp/preview'
    | '/_authenticated/invitations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  RestaurantsRoute: typeof RestaurantsRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
  RsvpPreviewRoute: typeof RsvpPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/preview': {
      id: '/rsvp/preview'
      path: '/rsvp/preview'
      fullPath: '/rsvp/preview'
      preLoaderRoute: typeof RsvpPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitations/new': {
      id: '/_authenticated/invitations/new'
      path: '/invitations/new'
      fullPath: '/invitations/new'
      preLoaderRoute: typeof AuthenticatedInvitationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvitationsNewRoute: typeof AuthenticatedInvitationsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvitationsNewRoute: AuthenticatedInvitationsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  RestaurantsRoute: RestaurantsRoute,
  RsvpTokenRoute: RsvpTokenRoute,
  RsvpPreviewRoute: RsvpPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
